
# POST https://sandbox.bluesnap.com/services/2/tools/param-encryption HTTP/1.0
# Content-Type: application/xml
# Authorization: Basic QVBJXzE2MTUyOTMzODA2ODMyMjA2MTMzMzM6UWFRYTEyMyQ=

# <param-encryption xmlns="http://ws.plimus.com">
#   <parameters>
#     <parameter>
#       <param-key>amount</param-key>
#       <param-value>120.00</param-value>
#     </parameter>
#   </parameters>
# </param-encryption>



POST https://sandbox.bluesnap.com/services/2/payment-fields-tokens HTTP/1.0
Content-Type: application/json
Accept: application/json
Authorization: Basic QVBJXzE2MTUyOTMzODA2ODMyMjA2MTMzMzM6UWFRYTEyMyQ=
'

# POST https://sandbox.bluesnap.com/services/2/recurring/plans HTTP/1.0
# Content-Type: application/json
# Accept: application/json
# Authorization: Basic QVBJXzE2MTU0NzI5MDQ1NTgzNzIyMTcyNjg6UWFRYTEyMyQ=
# Content-Length: 278

# {
#     "chargeFrequency": "MONTHLY",
#     "name": "30 Credits Monthly",
#     "currency": "USD",
#     "recurringChargeAmount": 99.99
# }

